name: nvc_cinemas
description: NVC Cinemas

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^1.0.3
  intl: ^0.17.0
  meta: ^1.7.0
  dio: ^4.0.4
  json_annotation: ^4.4.0
  pretty_dio_logger: ^1.1.1
  flutter_secure_storage: 5.0.2
  lottie: ^1.2.1
  shared_preferences: ^2.0.12
  flutter_dotenv: ^5.0.2
  flutter_svg: ^1.0.3
  flutter_svg_provider: ^1.0.3
  rounded_loading_button: ^2.1.0
  reactive_forms: ^13.0.0
  one_context: ^2.0.0
  rflutter_alert: ^2.0.4
  gradient_like_css: ^1.0.1
  timeline_tile: ^2.0.0
  # audioplayers: ^1.0.1
  flutter_dash: ^1.0.0
  # flag country
  country_icons: ^2.0.2
  shimmer: ^2.0.0
  # launcher
  url_launcher: ^6.1.6
  month_year_picker: ^0.2.0+3
  logger: ^1.0.0
  parser_error: ^0.2.0
  path: ^1.6.4
  uuid: ^3.0.7
  permission_handler_platform_interface: ^3.9.0
  permission_handler: ^10.2.0
  # html to text, editing text
  simple_html_css: ^4.0.0
  diacritic: ^0.1.3
  # pick file
  file_picker: ^5.2.1
  path_provider: ^2.0.11
  # GetX
  get:
  # foreground - background -> push notification
  flutter_foreground_task: ^3.10.0
  firebase_messaging: ^14.2.1
  flutter_local_notifications: ^13.0.0
  firebase_core: ^2.4.1
  # check device
  safe_device: ^1.1.2
  device_info_plus: ^8.1.0
  # check connectivity
  connectivity_plus: ^2.3.9
  #scroll
  scroll_app_bar: ^2.0.0
  lazy_load_scrollview: ^1.3.0
  card_swiper: ^2.0.1
  # copy
  clipboard: ^0.1.3
  # pick image
  image_picker: ^0.8.3+1
  # star rating
  flutter_rating_bar: ^4.0.1
  #chart
  syncfusion_flutter_charts: ^19.2.4
  #qr generate
  qr_flutter: ^4.0.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.0
  dart_code_metrics: ^4.8.1
  very_good_performance: ^0.0.4
  dependency_validator: ^3.1.2
  json_serializable:
  build_runner:
  flutter_gen_runner:
  freezed: ^2.0.3
  # logger:
  import_sorter: ^4.6.0
  flutter_launcher_icons:
  # call
  lints: ^1.0.1
  test: ^1.6.7

scripts: derry.yaml

# https://pub.dev/packages/flutter_gen, after new assets run derry gen
flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  integrations:
    flutter_svg: true
  #  integrations:
  #    flutter_svg: true
  #    flare_flutter: true

  assets:
    enabled: true
  fonts:
    enabled: true
  colors:
    enabled: true
    inputs:
      - assets/color/colors.xml
import_sorter:
  comments: false # Optional, defaults to true
  ignored_files: # Optional, defaults to []
    - \/lib\/*
flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/env/.env.production
    - assets/env/
    - assets/
    - assets/images/
  fonts:
    - family: CircularStd
      fonts:
        - asset: assets/fonts/CircularStd-Book.otf
        - asset: assets/fonts/CircularStd-Bold.otf
          weight: 700

flutter_icons:
  image_path: "assets/images/icon-1024x1024.png"
  android: true
  ios: true
